//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 07:01:27 PM CET 
//


package com.spring.rest.model.izvestaj;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pocetni_datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="zavrsni_datum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_dokumenata_imunizaciju" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="izdati_zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="raspored_doza_vakcina_broj_doze" type="{http://www.ftn-vakcine.rs/izvestaj}raspored_doza_broj"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/izvestaj}raspored_doza_vakcina_proizvodjac"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pocetniDatum",
    "zavrsniDatum",
    "brojDokumenataImunizaciju",
    "zahteviSertifikat",
    "izdatiZahteviSertifikat",
    "brojDoza",
    "rasporedDozaVakcinaBrojDoze",
    "rasporedDozaVakcinaProizvodjac",
    "datum",
    "potpis"
})
@XmlRootElement(name = "izvestaj_o_imunizaciji")
public class IzvestajOImunizaciji {

    @XmlElement(name = "pocetni_datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pocetniDatum;
    @XmlElement(name = "zavrsni_datum", required = true)
    protected XMLGregorianCalendar zavrsniDatum;
    @XmlElement(name = "broj_dokumenata_imunizaciju", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojDokumenataImunizaciju;
    @XmlElement(name = "zahtevi_sertifikat", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger zahteviSertifikat;
    @XmlElement(name = "izdati_zahtevi_sertifikat", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger izdatiZahteviSertifikat;
    @XmlElement(name = "broj_doza", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojDoza;
    @XmlElement(name = "raspored_doza_vakcina_broj_doze", required = true)
    protected RasporedDozaBroj rasporedDozaVakcinaBrojDoze;
    @XmlElement(name = "raspored_doza_vakcina_proizvodjac", required = true)
    protected RasporedDozaProizvodjac rasporedDozaVakcinaProizvodjac;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected String potpis;

    /**
     * Gets the value of the pocetniDatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPocetniDatum() {
        return pocetniDatum;
    }

    /**
     * Sets the value of the pocetniDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPocetniDatum(XMLGregorianCalendar value) {
        this.pocetniDatum = value;
    }

    /**
     * Gets the value of the zavrsniDatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getZavrsniDatum() {
        return zavrsniDatum;
    }

    /**
     * Sets the value of the zavrsniDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setZavrsniDatum(XMLGregorianCalendar value) {
        this.zavrsniDatum = value;
    }

    /**
     * Gets the value of the brojDokumenataImunizaciju property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDokumenataImunizaciju() {
        return brojDokumenataImunizaciju;
    }

    /**
     * Sets the value of the brojDokumenataImunizaciju property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDokumenataImunizaciju(BigInteger value) {
        this.brojDokumenataImunizaciju = value;
    }

    /**
     * Gets the value of the zahteviSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZahteviSertifikat() {
        return zahteviSertifikat;
    }

    /**
     * Sets the value of the zahteviSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZahteviSertifikat(BigInteger value) {
        this.zahteviSertifikat = value;
    }

    /**
     * Gets the value of the izdatiZahteviSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIzdatiZahteviSertifikat() {
        return izdatiZahteviSertifikat;
    }

    /**
     * Sets the value of the izdatiZahteviSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIzdatiZahteviSertifikat(BigInteger value) {
        this.izdatiZahteviSertifikat = value;
    }

    /**
     * Gets the value of the brojDoza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDoza() {
        return brojDoza;
    }

    /**
     * Sets the value of the brojDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDoza(BigInteger value) {
        this.brojDoza = value;
    }

    /**
     * Gets the value of the rasporedDozaVakcinaBrojDoze property.
     * 
     * @return
     *     possible object is
     *     {@link RasporedDozaBroj }
     *     
     */
    public RasporedDozaBroj getRasporedDozaVakcinaBrojDoze() {
        return rasporedDozaVakcinaBrojDoze;
    }

    /**
     * Sets the value of the rasporedDozaVakcinaBrojDoze property.
     * 
     * @param value
     *     allowed object is
     *     {@link RasporedDozaBroj }
     *     
     */
    public void setRasporedDozaVakcinaBrojDoze(RasporedDozaBroj value) {
        this.rasporedDozaVakcinaBrojDoze = value;
    }

    /**
     * Gets the value of the rasporedDozaVakcinaProizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link RasporedDozaProizvodjac }
     *     
     */
    public RasporedDozaProizvodjac getRasporedDozaVakcinaProizvodjac() {
        return rasporedDozaVakcinaProizvodjac;
    }

    /**
     * Sets the value of the rasporedDozaVakcinaProizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link RasporedDozaProizvodjac }
     *     
     */
    public void setRasporedDozaVakcinaProizvodjac(RasporedDozaProizvodjac value) {
        this.rasporedDozaVakcinaProizvodjac = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

}
