//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:54:34 PM CET 
//


package com.spring.rest.model.izvestaj;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the izvestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RasporedDozaVakcinaProizvodjac_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "raspored_doza_vakcina_proizvodjac");
    private final static QName _InfoProizvodjac_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "info_proizvodjac");
    private final static QName _InfoDoza_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "info_doza");
    private final static QName _RasporedDozaVakcinaBrojDoze_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "raspored_doza_vakcina_broj_doze");
    private final static QName _IzvestajOImunizacijiIzdatiZahteviSertifikat_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "izdati_zahtevi_sertifikat");
    private final static QName _IzvestajOImunizacijiPocetniDatum_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "pocetni_datum");
    private final static QName _IzvestajOImunizacijiZavrsniDatum_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "zavrsni_datum");
    private final static QName _IzvestajOImunizacijiZahteviSertifikat_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "zahtevi_sertifikat");
    private final static QName _IzvestajOImunizacijiBrojDoza_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "broj_doza");
    private final static QName _IzvestajOImunizacijiDatum_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "datum");
    private final static QName _IzvestajOImunizacijiBrojDokumenataImunizaciju_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "broj_dokumenata_imunizaciju");
    private final static QName _IzvestajOImunizacijiPotpis_QNAME = new QName("http://www.ftn-vakcine.rs/izvestaj", "potpis");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: izvestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TProizvodjac }
     * 
     */
    public TProizvodjac createTProizvodjac() {
        return new TProizvodjac();
    }

    /**
     * Create an instance of {@link TDoza }
     * 
     */
    public TDoza createTDoza() {
        return new TDoza();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     * 
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link RasporedDozaProizvodjac }
     * 
     */
    public RasporedDozaProizvodjac createRasporedDozaProizvodjac() {
        return new RasporedDozaProizvodjac();
    }

    /**
     * Create an instance of {@link RasporedDozaBroj }
     * 
     */
    public RasporedDozaBroj createRasporedDozaBroj() {
        return new RasporedDozaBroj();
    }

    /**
     * Create an instance of {@link ImePrezime }
     * 
     */
    public ImePrezime createImePrezime() {
        return new ImePrezime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RasporedDozaProizvodjac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "raspored_doza_vakcina_proizvodjac")
    public JAXBElement<RasporedDozaProizvodjac> createRasporedDozaVakcinaProizvodjac(RasporedDozaProizvodjac value) {
        return new JAXBElement<RasporedDozaProizvodjac>(_RasporedDozaVakcinaProizvodjac_QNAME, RasporedDozaProizvodjac.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProizvodjac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "info_proizvodjac")
    public JAXBElement<TProizvodjac> createInfoProizvodjac(TProizvodjac value) {
        return new JAXBElement<TProizvodjac>(_InfoProizvodjac_QNAME, TProizvodjac.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDoza }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "info_doza")
    public JAXBElement<TDoza> createInfoDoza(TDoza value) {
        return new JAXBElement<TDoza>(_InfoDoza_QNAME, TDoza.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RasporedDozaBroj }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "raspored_doza_vakcina_broj_doze")
    public JAXBElement<RasporedDozaBroj> createRasporedDozaVakcinaBrojDoze(RasporedDozaBroj value) {
        return new JAXBElement<RasporedDozaBroj>(_RasporedDozaVakcinaBrojDoze_QNAME, RasporedDozaBroj.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "izdati_zahtevi_sertifikat", scope = IzvestajOImunizaciji.class)
    public JAXBElement<BigInteger> createIzvestajOImunizacijiIzdatiZahteviSertifikat(BigInteger value) {
        return new JAXBElement<BigInteger>(_IzvestajOImunizacijiIzdatiZahteviSertifikat_QNAME, BigInteger.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "pocetni_datum", scope = IzvestajOImunizaciji.class)
    public JAXBElement<XMLGregorianCalendar> createIzvestajOImunizacijiPocetniDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IzvestajOImunizacijiPocetniDatum_QNAME, XMLGregorianCalendar.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "zavrsni_datum", scope = IzvestajOImunizaciji.class)
    public JAXBElement<XMLGregorianCalendar> createIzvestajOImunizacijiZavrsniDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IzvestajOImunizacijiZavrsniDatum_QNAME, XMLGregorianCalendar.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "zahtevi_sertifikat", scope = IzvestajOImunizaciji.class)
    public JAXBElement<BigInteger> createIzvestajOImunizacijiZahteviSertifikat(BigInteger value) {
        return new JAXBElement<BigInteger>(_IzvestajOImunizacijiZahteviSertifikat_QNAME, BigInteger.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "broj_doza", scope = IzvestajOImunizaciji.class)
    public JAXBElement<BigInteger> createIzvestajOImunizacijiBrojDoza(BigInteger value) {
        return new JAXBElement<BigInteger>(_IzvestajOImunizacijiBrojDoza_QNAME, BigInteger.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "datum", scope = IzvestajOImunizaciji.class)
    public JAXBElement<XMLGregorianCalendar> createIzvestajOImunizacijiDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IzvestajOImunizacijiDatum_QNAME, XMLGregorianCalendar.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "broj_dokumenata_imunizaciju", scope = IzvestajOImunizaciji.class)
    public JAXBElement<BigInteger> createIzvestajOImunizacijiBrojDokumenataImunizaciju(BigInteger value) {
        return new JAXBElement<BigInteger>(_IzvestajOImunizacijiBrojDokumenataImunizaciju_QNAME, BigInteger.class, IzvestajOImunizaciji.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/izvestaj", name = "potpis", scope = IzvestajOImunizaciji.class)
    public JAXBElement<String> createIzvestajOImunizacijiPotpis(String value) {
        return new JAXBElement<String>(_IzvestajOImunizacijiPotpis_QNAME, String.class, IzvestajOImunizaciji.class, value);
    }

}
