//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< Updated upstream:Spring-JAX-RS/src/main/java/com/spring/rest/model/izvestaj/package-info.java
// Generated on: 2022.01.12 at 07:35:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/vakcina/izvestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spring.rest.model.izvestaj;
=======
// Generated on: 2022.01.05 at 01:47:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn-vakcine.rs/izvestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.types;
>>>>>>> Stashed changes:Spring-JAX-RS/src/main/java/model/types/package-info.java
