//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:36:09 PM CET 
//


package com.spring.rest.model.zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.vakcina.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.vakcina.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat }
     * 
     */
    public ZahtevZaSertifikat createZahtevZaSertifikat() {
        return new ZahtevZaSertifikat();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.LicniPodaci }
     * 
     */
    public ZahtevZaSertifikat.LicniPodaci createZahtevZaSertifikatLicniPodaci() {
        return new ZahtevZaSertifikat.LicniPodaci();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.Mesto }
     * 
     */
    public ZahtevZaSertifikat.Mesto createZahtevZaSertifikatMesto() {
        return new ZahtevZaSertifikat.Mesto();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.DatumZahteva }
     * 
     */
    public ZahtevZaSertifikat.DatumZahteva createZahtevZaSertifikatDatumZahteva() {
        return new ZahtevZaSertifikat.DatumZahteva();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.LicniPodaci.JMBG }
     * 
     */
    public ZahtevZaSertifikat.LicniPodaci.JMBG createZahtevZaSertifikatLicniPodaciJMBG() {
        return new ZahtevZaSertifikat.LicniPodaci.JMBG();
    }

}
