//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:35:31 PM CET 
//


package model.izvestaj;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pocetni_datum">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zavrsni_datum">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="broj_dokumenata_imunizaciju" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="izdati_zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="raspored_doza_vakcina_broj_doze" type="{http://ftn.uns.ac.rs/vakcina/izvestaj}raspored_doza_broj"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/izvestaj}raspored_doza_vakcina_proizvodjac"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pocetniDatum",
    "zavrsniDatum",
    "brojDokumenataImunizaciju",
    "zahteviSertifikat",
    "izdatiZahteviSertifikat",
    "brojDoza",
    "rasporedDozaVakcinaBrojDoze",
    "rasporedDozaVakcinaProizvodjac",
    "datum",
    "potpis"
})
@XmlRootElement(name = "izvestaj_o_imunizaciji")
public class IzvestajOImunizaciji {

    @XmlElement(name = "pocetni_datum", required = true)
    protected PocetniDatum pocetniDatum;
    @XmlElement(name = "zavrsni_datum", required = true)
    protected ZavrsniDatum zavrsniDatum;
    @XmlElement(name = "broj_dokumenata_imunizaciju", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojDokumenataImunizaciju;
    @XmlElement(name = "zahtevi_sertifikat", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger zahteviSertifikat;
    @XmlElement(name = "izdati_zahtevi_sertifikat", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger izdatiZahteviSertifikat;
    @XmlElement(name = "broj_doza", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojDoza;
    @XmlElement(name = "raspored_doza_vakcina_broj_doze", required = true)
    protected RasporedDozaBroj rasporedDozaVakcinaBrojDoze;
    @XmlElement(name = "raspored_doza_vakcina_proizvodjac", required = true)
    protected RasporedDozaProizvodjac rasporedDozaVakcinaProizvodjac;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected String potpis;

    /**
     * Gets the value of the pocetniDatum property.
     * 
     * @return
     *     possible object is
     *     {@link PocetniDatum }
     *     
     */
    public PocetniDatum getPocetniDatum() {
        return pocetniDatum;
    }

    /**
     * Sets the value of the pocetniDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link PocetniDatum }
     *     
     */
    public void setPocetniDatum(PocetniDatum value) {
        this.pocetniDatum = value;
    }

    /**
     * Gets the value of the zavrsniDatum property.
     * 
     * @return
     *     possible object is
     *     {@link ZavrsniDatum }
     *     
     */
    public ZavrsniDatum getZavrsniDatum() {
        return zavrsniDatum;
    }

    /**
     * Sets the value of the zavrsniDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZavrsniDatum }
     *     
     */
    public void setZavrsniDatum(ZavrsniDatum value) {
        this.zavrsniDatum = value;
    }

    /**
     * Gets the value of the brojDokumenataImunizaciju property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDokumenataImunizaciju() {
        return brojDokumenataImunizaciju;
    }

    /**
     * Sets the value of the brojDokumenataImunizaciju property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDokumenataImunizaciju(BigInteger value) {
        this.brojDokumenataImunizaciju = value;
    }

    /**
     * Gets the value of the zahteviSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZahteviSertifikat() {
        return zahteviSertifikat;
    }

    /**
     * Sets the value of the zahteviSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZahteviSertifikat(BigInteger value) {
        this.zahteviSertifikat = value;
    }

    /**
     * Gets the value of the izdatiZahteviSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIzdatiZahteviSertifikat() {
        return izdatiZahteviSertifikat;
    }

    /**
     * Sets the value of the izdatiZahteviSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIzdatiZahteviSertifikat(BigInteger value) {
        this.izdatiZahteviSertifikat = value;
    }

    /**
     * Gets the value of the brojDoza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDoza() {
        return brojDoza;
    }

    /**
     * Sets the value of the brojDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDoza(BigInteger value) {
        this.brojDoza = value;
    }

    /**
     * Gets the value of the rasporedDozaVakcinaBrojDoze property.
     * 
     * @return
     *     possible object is
     *     {@link RasporedDozaBroj }
     *     
     */
    public RasporedDozaBroj getRasporedDozaVakcinaBrojDoze() {
        return rasporedDozaVakcinaBrojDoze;
    }

    /**
     * Sets the value of the rasporedDozaVakcinaBrojDoze property.
     * 
     * @param value
     *     allowed object is
     *     {@link RasporedDozaBroj }
     *     
     */
    public void setRasporedDozaVakcinaBrojDoze(RasporedDozaBroj value) {
        this.rasporedDozaVakcinaBrojDoze = value;
    }

    /**
     * Gets the value of the rasporedDozaVakcinaProizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link RasporedDozaProizvodjac }
     *     
     */
    public RasporedDozaProizvodjac getRasporedDozaVakcinaProizvodjac() {
        return rasporedDozaVakcinaProizvodjac;
    }

    /**
     * Sets the value of the rasporedDozaVakcinaProizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link RasporedDozaProizvodjac }
     *     
     */
    public void setRasporedDozaVakcinaProizvodjac(RasporedDozaProizvodjac value) {
        this.rasporedDozaVakcinaProizvodjac = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    @Override
    public String toString() {
        return "IzvestajOImunizaciji{" +
                "pocetniDatum=" + pocetniDatum +
                ", zavrsniDatum=" + zavrsniDatum +
                ", brojDokumenataImunizaciju=" + brojDokumenataImunizaciju +
                ", zahteviSertifikat=" + zahteviSertifikat +
                ", izdatiZahteviSertifikat=" + izdatiZahteviSertifikat +
                ", brojDoza=" + brojDoza +
                ", rasporedDozaVakcinaBrojDoze=" + rasporedDozaVakcinaBrojDoze +
                ", rasporedDozaVakcinaProizvodjac=" + rasporedDozaVakcinaProizvodjac +
                ", datum=" + datum +
                ", potpis='" + potpis + '\'' +
                '}';
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PocetniDatum {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ZavrsniDatum {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

}
