//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:54:34 PM CET 
//

<<<<<<< Updated upstream:Spring-JAX-RS/src/main/java/com/spring/rest/model/izvestaj/package-info.java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn-vakcine.rs/izvestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spring.rest.model.izvestaj;
=======
@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/vakcina/izvestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.izvestaj;
>>>>>>> Stashed changes:Spring-JAX-RS/src/main/java/model/izvestaj/package-info.java
