//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.05 at 01:47:54 PM CET 
//


package types;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pocetni_datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="zavrsni_datum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_dokumenata_imunizaciju" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="izdati_zahtevi_sertifikat" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="broj_doza" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/izvestaj}raspored_doza_vakcina_proizvodjac"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/izvestaj}raspored_doza_vakcina_proizvodjac"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "izvestaj_o_imunizaciji")
public class IzvestajOImunizaciji {

    @XmlElementRefs({
        @XmlElementRef(name = "izdati_zahtevi_sertifikat", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pocetni_datum", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "zavrsni_datum", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "potpis", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datum", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "broj_dokumenata_imunizaciju", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "zahtevi_sertifikat", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "broj_doza", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "raspored_doza_vakcina_proizvodjac", namespace = "http://www.ftn-vakcine.rs/izvestaj", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "RasporedDozaVakcinaProizvodjac" is used by two different parts of a schema. See: 
     * line 22 of file:/D:/faks/4godina/xmlWebServiS/projekat/XML/schemas/izvestaj.xsd
     * line 21 of file:/D:/faks/4godina/xmlWebServiS/projekat/XML/schemas/izvestaj.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link RasporedDozaProizvodjac }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
