//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:53:55 PM CET 
//


package com.spring.rest.model.interesovanje;

import com.spring.rest.model.types.*;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licni_podaci">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="drzavljanstvo">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Drzavljanin_RS"/>
 *                         &lt;enumeration value="Strani_bez_boravka"/>
 *                         &lt;enumeration value="Strani_sa_boravkom"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="JMBG" type="{http://www.ftn-vakcine.rs/types}JMBG"/>
 *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.ftn-vakcine.rs/types}email"/>
 *                   &lt;element name="mobilni_telefon" type="{http://www.ftn-vakcine.rs/types}mobilni_telefon"/>
 *                   &lt;element name="fiksni_telefon" type="{http://www.ftn-vakcine.rs/types}fiksni_telefon"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lokacija_vakcinisanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tip_vakcine" type="{http://www.ftn-vakcine.rs/types}tip_vakcine"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="davalac_krvi" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="potvrda_o_vakcinisanju" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="saglasnost_za_imunizaciju" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licniPodaci",
    "lokacijaVakcinisanja",
    "tipVakcine",
    "datum",
    "potpis",
    "davalacKrvi"
})
@XmlRootElement(name = "interesovanje")
public class Interesovanje {

    @XmlElement(name = "licni_podaci", required = true)
    protected LicniPodaci licniPodaci;
    @XmlElement(name = "lokacija_vakcinisanja", required = true)
    protected String lokacijaVakcinisanja;
    @XmlElement(name = "tip_vakcine", required = true)
    @XmlSchemaType(name = "string")
    protected TipVakcine tipVakcine;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected String potpis;
    @XmlElement(name = "davalac_krvi")
    protected Object davalacKrvi;
    @XmlAttribute(name = "potvrda_o_vakcinisanju")
    @XmlSchemaType(name = "anySimpleType")
    protected String potvrdaOVakcinisanju;
    @XmlAttribute(name = "saglasnost_za_imunizaciju")
    @XmlSchemaType(name = "anySimpleType")
    protected String saglasnostZaImunizaciju;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link LicniPodaci }
     *     
     */
    public LicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicniPodaci }
     *     
     */
    public void setLicniPodaci(LicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the lokacijaVakcinisanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLokacijaVakcinisanja() {
        return lokacijaVakcinisanja;
    }

    /**
     * Sets the value of the lokacijaVakcinisanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLokacijaVakcinisanja(String value) {
        this.lokacijaVakcinisanja = value;
    }

    /**
     * Gets the value of the tipVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TipVakcine }
     *     
     */
    public TipVakcine getTipVakcine() {
        return tipVakcine;
    }

    /**
     * Sets the value of the tipVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipVakcine }
     *     
     */
    public void setTipVakcine(TipVakcine value) {
        this.tipVakcine = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the davalacKrvi property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDavalacKrvi() {
        return davalacKrvi;
    }

    /**
     * Sets the value of the davalacKrvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDavalacKrvi(Object value) {
        this.davalacKrvi = value;
    }

    /**
     * Gets the value of the potvrdaOVakcinisanju property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotvrdaOVakcinisanju() {
        return potvrdaOVakcinisanju;
    }

    /**
     * Sets the value of the potvrdaOVakcinisanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotvrdaOVakcinisanju(String value) {
        this.potvrdaOVakcinisanju = value;
    }

    /**
     * Gets the value of the saglasnostZaImunizaciju property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaglasnostZaImunizaciju() {
        return saglasnostZaImunizaciju;
    }

    /**
     * Sets the value of the saglasnostZaImunizaciju property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaglasnostZaImunizaciju(String value) {
        this.saglasnostZaImunizaciju = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="drzavljanstvo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Drzavljanin_RS"/>
     *               &lt;enumeration value="Strani_bez_boravka"/>
     *               &lt;enumeration value="Strani_sa_boravkom"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="JMBG" type="{http://www.ftn-vakcine.rs/types}JMBG"/>
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.ftn-vakcine.rs/types}email"/>
     *         &lt;element name="mobilni_telefon" type="{http://www.ftn-vakcine.rs/types}mobilni_telefon"/>
     *         &lt;element name="fiksni_telefon" type="{http://www.ftn-vakcine.rs/types}fiksni_telefon"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drzavljanstvo",
        "jmbg",
        "ime",
        "prezime",
        "email",
        "mobilniTelefon",
        "fiksniTelefon"
    })
    public static class LicniPodaci {

        @XmlElement(required = true)
        protected String drzavljanstvo;
        @XmlElement(name = "JMBG", required = true)
        protected String jmbg;
        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(name = "mobilni_telefon", required = true)
        protected String mobilniTelefon;
        @XmlElement(name = "fiksni_telefon", required = true)
        protected String fiksniTelefon;

        /**
         * Gets the value of the drzavljanstvo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrzavljanstvo(String value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the jmbg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJMBG() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJMBG(String value) {
            this.jmbg = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the mobilniTelefon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMobilniTelefon() {
            return mobilniTelefon;
        }

        /**
         * Sets the value of the mobilniTelefon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMobilniTelefon(String value) {
            this.mobilniTelefon = value;
        }

        /**
         * Gets the value of the fiksniTelefon property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFiksniTelefon() {
            return fiksniTelefon;
        }

        /**
         * Sets the value of the fiksniTelefon property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFiksniTelefon(String value) {
            this.fiksniTelefon = value;
        }

    }

}
