//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:41:55 PM CET 
//


package model.saglasnost;


import model.tipovi.Pol;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}drzavljanstvo"/>
 *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pol">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://ftn.uns.ac.rs/vakcina/tipovi}pol">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresa">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ulica_broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mesto_naselje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="opstina_grad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fiksni_broj" type="{http://ftn.uns.ac.rs/vakcina/tipovi}fiksni_telefon"/>
 *         &lt;element name="mobilni_broj" type="{http://ftn.uns.ac.rs/vakcina/tipovi}mobilni_telefon"/>
 *         &lt;element name="email" type="{http://ftn.uns.ac.rs/vakcina/tipovi}email"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}radni_status"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}zanimanje_zaposlenog" minOccurs="0"/>
 *         &lt;element name="korisnik_soc_zastite" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naziv_opstine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "prezime",
    "ime",
    "imeRoditelja",
    "pol",
    "datumRodjenja",
    "mestoRodjenja",
    "adresa",
    "fiksniBroj",
    "mobilniBroj",
    "email",
    "radniStatus",
    "zanimanjeZaposlenog",
    "korisnikSocZastite"
})
@XmlRootElement(name = "licni_podaci")
public class LicniPodaci {

    @XmlElement(required = true)
    protected Drzavljanstvo drzavljanstvo;
    @XmlElement(required = true)
    protected String prezime;
    @XmlElement(required = true)
    protected String ime;
    @XmlElement(name = "ime_roditelja", required = true)
    protected String imeRoditelja;
    @XmlElement(required = true)
    protected Pol pol;
    @XmlElement(name = "datum_rodjenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRodjenja;
    @XmlElement(name = "mesto_rodjenja", required = true)
    protected String mestoRodjenja;
    @XmlElement(required = true)
    protected Adresa adresa;
    @XmlElement(name = "fiksni_broj", required = true)
    protected String fiksniBroj;
    @XmlElement(name = "mobilni_broj", required = true)
    protected String mobilniBroj;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(name = "radni_status", required = true)
    protected String radniStatus;
    @XmlElement(name = "zanimanje_zaposlenog")
    protected String zanimanjeZaposlenog;
    @XmlElement(name = "korisnik_soc_zastite")
    protected KorisnikSocZastite korisnikSocZastite;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link Drzavljanstvo }
     *     
     */
    public Drzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo }
     *     
     */
    public void setDrzavljanstvo(Drzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the imeRoditelja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeRoditelja() {
        return imeRoditelja;
    }

    /**
     * Sets the value of the imeRoditelja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeRoditelja(String value) {
        this.imeRoditelja = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link Pol }
     *     
     */
    public Pol getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pol }
     *     
     */
    public void setPol(Pol value) {
        this.pol = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRodjenja(XMLGregorianCalendar value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the mestoRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMestoRodjenja() {
        return mestoRodjenja;
    }

    /**
     * Sets the value of the mestoRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMestoRodjenja(String value) {
        this.mestoRodjenja = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link Adresa }
     *     
     */
    public Adresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adresa }
     *     
     */
    public void setAdresa(Adresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the fiksniBroj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiksniBroj() {
        return fiksniBroj;
    }

    /**
     * Sets the value of the fiksniBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiksniBroj(String value) {
        this.fiksniBroj = value;
    }

    /**
     * Gets the value of the mobilniBroj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilniBroj() {
        return mobilniBroj;
    }

    /**
     * Sets the value of the mobilniBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilniBroj(String value) {
        this.mobilniBroj = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the radniStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadniStatus() {
        return radniStatus;
    }

    /**
     * Sets the value of the radniStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadniStatus(String value) {
        this.radniStatus = value;
    }

    /**
     * Gets the value of the zanimanjeZaposlenog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZanimanjeZaposlenog() {
        return zanimanjeZaposlenog;
    }

    /**
     * Sets the value of the zanimanjeZaposlenog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZanimanjeZaposlenog(String value) {
        this.zanimanjeZaposlenog = value;
    }

    /**
     * Gets the value of the korisnikSocZastite property.
     * 
     * @return
     *     possible object is
     *     {@link KorisnikSocZastite }
     *     
     */
    public KorisnikSocZastite getKorisnikSocZastite() {
        return korisnikSocZastite;
    }

    /**
     * Sets the value of the korisnikSocZastite property.
     * 
     * @param value
     *     allowed object is
     *     {@link KorisnikSocZastite }
     *     
     */
    public void setKorisnikSocZastite(KorisnikSocZastite value) {
        this.korisnikSocZastite = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ulica_broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mesto_naselje" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="opstina_grad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ulicaBroj",
        "mestoNaselje",
        "opstinaGrad"
    })
    public static class Adresa {

        @XmlElement(name = "ulica_broj", required = true)
        protected String ulicaBroj;
        @XmlElement(name = "mesto_naselje", required = true)
        protected String mestoNaselje;
        @XmlElement(name = "opstina_grad", required = true)
        protected String opstinaGrad;

        /**
         * Gets the value of the ulicaBroj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUlicaBroj() {
            return ulicaBroj;
        }

        /**
         * Sets the value of the ulicaBroj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUlicaBroj(String value) {
            this.ulicaBroj = value;
        }

        /**
         * Gets the value of the mestoNaselje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMestoNaselje() {
            return mestoNaselje;
        }

        /**
         * Sets the value of the mestoNaselje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMestoNaselje(String value) {
            this.mestoNaselje = value;
        }

        /**
         * Gets the value of the opstinaGrad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpstinaGrad() {
            return opstinaGrad;
        }

        /**
         * Sets the value of the opstinaGrad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpstinaGrad(String value) {
            this.opstinaGrad = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naziv_opstine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivOpstine"
    })
    public static class KorisnikSocZastite {

        @XmlElement(name = "naziv_opstine", required = true)
        protected String nazivOpstine;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the nazivOpstine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivOpstine() {
            return nazivOpstine;
        }

        /**
         * Sets the value of the nazivOpstine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivOpstine(String value) {
            this.nazivOpstine = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

}
