//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:41:55 PM CET 
//


package com.spring.rest.model.saglasnost;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vakcinijski_punkt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}lekar"/>
 *         &lt;element name="tabela_vakcinisanja">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}vakcinisanje" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zdravstvenaUstanova",
    "vakcinijskiPunkt",
    "lekar",
    "tabelaVakcinisanja"
})
@XmlRootElement(name = "evidencija_o_vakcinaciji")
public class EvidencijaOVakcinaciji {

    @XmlElement(name = "zdravstvena_ustanova", required = true)
    protected String zdravstvenaUstanova;
    @XmlElement(name = "vakcinijski_punkt", required = true)
    protected String vakcinijskiPunkt;
    @XmlElement(required = true)
    protected TLekar lekar;
    @XmlElement(name = "tabela_vakcinisanja", required = true)
    protected TabelaVakcinisanja tabelaVakcinisanja;

    /**
     * Gets the value of the zdravstvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZdravstvenaUstanova() {
        return zdravstvenaUstanova;
    }

    /**
     * Sets the value of the zdravstvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZdravstvenaUstanova(String value) {
        this.zdravstvenaUstanova = value;
    }

    /**
     * Gets the value of the vakcinijskiPunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVakcinijskiPunkt() {
        return vakcinijskiPunkt;
    }

    /**
     * Sets the value of the vakcinijskiPunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVakcinijskiPunkt(String value) {
        this.vakcinijskiPunkt = value;
    }

    /**
     * Gets the value of the lekar property.
     * 
     * @return
     *     possible object is
     *     {@link TLekar }
     *     
     */
    public TLekar getLekar() {
        return lekar;
    }

    /**
     * Sets the value of the lekar property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLekar }
     *     
     */
    public void setLekar(TLekar value) {
        this.lekar = value;
    }

    /**
     * Gets the value of the tabelaVakcinisanja property.
     * 
     * @return
     *     possible object is
     *     {@link TabelaVakcinisanja }
     *     
     */
    public TabelaVakcinisanja getTabelaVakcinisanja() {
        return tabelaVakcinisanja;
    }

    /**
     * Sets the value of the tabelaVakcinisanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TabelaVakcinisanja }
     *     
     */
    public void setTabelaVakcinisanja(TabelaVakcinisanja value) {
        this.tabelaVakcinisanja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/saglasnost}vakcinisanje" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vakcinisanje"
    })
    public static class TabelaVakcinisanja {

        protected List<TVakcinisanje> vakcinisanje;

        /**
         * Gets the value of the vakcinisanje property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcinisanje property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcinisanje().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TVakcinisanje }
         * 
         * 
         */
        public List<TVakcinisanje> getVakcinisanje() {
            if (vakcinisanje == null) {
                vakcinisanje = new ArrayList<TVakcinisanje>();
            }
            return this.vakcinisanje;
        }

    }

}
