//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:58:55 PM CET 
//


package com.spring.rest.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naziv_drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broj_pasosa_ebs" type="{http://www.ftn-vakcine.rs/types}broj_pasosa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivDrzavljanstva",
    "brojPasosaEbs"
})
@XmlRootElement(name = "strano")
public class Strano {

    @XmlElement(name = "naziv_drzavljanstva", required = true)
    protected String nazivDrzavljanstva;
    @XmlElement(name = "broj_pasosa_ebs", required = true)
    protected String brojPasosaEbs;

    /**
     * Gets the value of the nazivDrzavljanstva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDrzavljanstva() {
        return nazivDrzavljanstva;
    }

    /**
     * Sets the value of the nazivDrzavljanstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDrzavljanstva(String value) {
        this.nazivDrzavljanstva = value;
    }

    /**
     * Gets the value of the brojPasosaEbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosaEbs() {
        return brojPasosaEbs;
    }

    /**
     * Sets the value of the brojPasosaEbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosaEbs(String value) {
        this.brojPasosaEbs = value;
    }

}
