//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:35:56 PM CET 
//


package com.spring.rest.model.potvrda;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informacije_vakcinacija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informacije_vakcinacija">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/potvrda}informacije_o_dozi" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informacije_vakcinacija", propOrder = {
    "informacijeODozi"
})
public class InformacijeVakcinacija {

    @XmlElement(name = "informacije_o_dozi", required = true)
    protected List<TInfomacijeODozi> informacijeODozi;

    /**
     * Gets the value of the informacijeODozi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informacijeODozi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformacijeODozi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInfomacijeODozi }
     * 
     * 
     */
    public List<TInfomacijeODozi> getInformacijeODozi() {
        if (informacijeODozi == null) {
            informacijeODozi = new ArrayList<TInfomacijeODozi>();
        }
        return this.informacijeODozi;
    }

}
