//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:55:55 PM CET 
//


package com.spring.rest.model.potvrda;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sifra_potvrde" type="{http://www.ftn-vakcine.rs/types}sifra"/>
 *         &lt;element name="licni_podaci" type="{http://www.ftn-vakcine.rs/potvrda}Licni_podaci"/>
 *         &lt;element name="informacije_vakcinacije" type="{http://www.ftn-vakcine.rs/potvrda}informacije_vakcinacija"/>
 *         &lt;element name="datum_izdavanja_potvrde" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qr_kod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="interesovanje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="saglanost_za_imunizaciju" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifraPotvrde",
    "licniPodaci",
    "informacijeVakcinacije",
    "datumIzdavanjaPotvrde",
    "zdravstvenaUstanova",
    "qrKod"
})
@XmlRootElement(name = "potvrda_o_vakcinaciji")
public class PotvrdaOVakcinaciji {

    @XmlElement(name = "sifra_potvrde", required = true)
    protected String sifraPotvrde;
    @XmlElement(name = "licni_podaci", required = true)
    protected LicniPodaci licniPodaci;
    @XmlElement(name = "informacije_vakcinacije", required = true)
    protected InformacijeVakcinacija informacijeVakcinacije;
    @XmlElement(name = "datum_izdavanja_potvrde", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanjaPotvrde;
    @XmlElement(name = "zdravstvena_ustanova", required = true)
    protected String zdravstvenaUstanova;
    @XmlElement(name = "qr_kod", required = true)
    protected String qrKod;
    @XmlAttribute(name = "interesovanje")
    @XmlSchemaType(name = "anySimpleType")
    protected String interesovanje;
    @XmlAttribute(name = "saglanost_za_imunizaciju")
    @XmlSchemaType(name = "anySimpleType")
    protected String saglanostZaImunizaciju;

    /**
     * Gets the value of the sifraPotvrde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraPotvrde() {
        return sifraPotvrde;
    }

    /**
     * Sets the value of the sifraPotvrde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraPotvrde(String value) {
        this.sifraPotvrde = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link LicniPodaci }
     *     
     */
    public LicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicniPodaci }
     *     
     */
    public void setLicniPodaci(LicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the informacijeVakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link InformacijeVakcinacija }
     *     
     */
    public InformacijeVakcinacija getInformacijeVakcinacije() {
        return informacijeVakcinacije;
    }

    /**
     * Sets the value of the informacijeVakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacijeVakcinacija }
     *     
     */
    public void setInformacijeVakcinacije(InformacijeVakcinacija value) {
        this.informacijeVakcinacije = value;
    }

    /**
     * Gets the value of the datumIzdavanjaPotvrde property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanjaPotvrde() {
        return datumIzdavanjaPotvrde;
    }

    /**
     * Sets the value of the datumIzdavanjaPotvrde property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanjaPotvrde(XMLGregorianCalendar value) {
        this.datumIzdavanjaPotvrde = value;
    }

    /**
     * Gets the value of the zdravstvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZdravstvenaUstanova() {
        return zdravstvenaUstanova;
    }

    /**
     * Sets the value of the zdravstvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZdravstvenaUstanova(String value) {
        this.zdravstvenaUstanova = value;
    }

    /**
     * Gets the value of the qrKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrKod(String value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the interesovanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteresovanje() {
        return interesovanje;
    }

    /**
     * Sets the value of the interesovanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteresovanje(String value) {
        this.interesovanje = value;
    }

    /**
     * Gets the value of the saglanostZaImunizaciju property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaglanostZaImunizaciju() {
        return saglanostZaImunizaciju;
    }

    /**
     * Sets the value of the saglanostZaImunizaciju property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaglanostZaImunizaciju(String value) {
        this.saglanostZaImunizaciju = value;
    }

}
