//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:57:22 PM CET 
//


package zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licni_podaci">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ime_prezime" type="{http://www.ftn-vakcine.rs/types}Ime_prezime"/>
 *                   &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="pol" type="{http://www.ftn-vakcine.rs/types}pol"/>
 *                   &lt;element name="JMBG">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ftn-vakcine.rs/types}JMBG">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="broj_pasosa">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ftn-vakcine.rs/types}broj_pasosa">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="razlog_za_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mesto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum_zahteva" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sertifikat" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licniPodaci",
    "razlogZaZahtev",
    "mesto",
    "datumZahteva",
    "potpis"
})
@XmlRootElement(name = "zahtev_za_sertifikat", namespace = "http://www.ftn-vakcine/zahtev_sertifikat")
public class ZahtevZaSertifikat {

    @XmlElement(name = "licni_podaci", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
    protected ZahtevZaSertifikat.LicniPodaci licniPodaci;
    @XmlElement(name = "razlog_za_zahtev", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
    protected String razlogZaZahtev;
    @XmlElement(namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
    protected String mesto;
    @XmlElement(name = "datum_zahteva", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZahteva;
    @XmlElement(namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
    protected String potpis;
    @XmlAttribute(name = "sertifikat")
    @XmlSchemaType(name = "anySimpleType")
    protected String sertifikat;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaSertifikat.LicniPodaci }
     *     
     */
    public ZahtevZaSertifikat.LicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaSertifikat.LicniPodaci }
     *     
     */
    public void setLicniPodaci(ZahtevZaSertifikat.LicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the razlogZaZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlogZaZahtev() {
        return razlogZaZahtev;
    }

    /**
     * Sets the value of the razlogZaZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlogZaZahtev(String value) {
        this.razlogZaZahtev = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZahteva(XMLGregorianCalendar value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the sertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSertifikat() {
        return sertifikat;
    }

    /**
     * Sets the value of the sertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSertifikat(String value) {
        this.sertifikat = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ime_prezime" type="{http://www.ftn-vakcine.rs/types}Ime_prezime"/>
     *         &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="pol" type="{http://www.ftn-vakcine.rs/types}pol"/>
     *         &lt;element name="JMBG">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ftn-vakcine.rs/types}JMBG">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="broj_pasosa">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ftn-vakcine.rs/types}broj_pasosa">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imePrezime",
        "datumRodjenja",
        "pol",
        "jmbg",
        "brojPasosa"
    })
    public static class LicniPodaci {

        @XmlElement(name = "ime_prezime", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
        protected ImePrezime imePrezime;
        @XmlElement(name = "datum_rodjenja", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumRodjenja;
        @XmlElement(namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
        @XmlSchemaType(name = "string")
        protected Pol pol;
        @XmlElement(name = "JMBG", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
        protected String jmbg;
        @XmlElement(name = "broj_pasosa", namespace = "http://www.ftn-vakcine/zahtev_sertifikat", required = true)
        protected String brojPasosa;

        /**
         * Gets the value of the imePrezime property.
         * 
         * @return
         *     possible object is
         *     {@link ImePrezime }
         *     
         */
        public ImePrezime getImePrezime() {
            return imePrezime;
        }

        /**
         * Sets the value of the imePrezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImePrezime }
         *     
         */
        public void setImePrezime(ImePrezime value) {
            this.imePrezime = value;
        }

        /**
         * Gets the value of the datumRodjenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumRodjenja() {
            return datumRodjenja;
        }

        /**
         * Sets the value of the datumRodjenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumRodjenja(XMLGregorianCalendar value) {
            this.datumRodjenja = value;
        }

        /**
         * Gets the value of the pol property.
         * 
         * @return
         *     possible object is
         *     {@link Pol }
         *     
         */
        public Pol getPol() {
            return pol;
        }

        /**
         * Sets the value of the pol property.
         * 
         * @param value
         *     allowed object is
         *     {@link Pol }
         *     
         */
        public void setPol(Pol value) {
            this.pol = value;
        }

        /**
         * Gets the value of the jmbg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJMBG() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJMBG(String value) {
            this.jmbg = value;
        }

        /**
         * Gets the value of the brojPasosa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPasosa() {
            return brojPasosa;
        }

        /**
         * Sets the value of the brojPasosa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPasosa(String value) {
            this.brojPasosa = value;
        }

    }

}
