//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:58:55 PM CET 
//


package saglasnost;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the saglasnost package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RadniStatus_QNAME = new QName("http://www.ftn-vakcine.rs/saglanost", "radni_status");
    private final static QName _Lekar_QNAME = new QName("http://www.ftn-vakcine.rs/saglanost", "lekar");
    private final static QName _ZanimanjeZaposlenog_QNAME = new QName("http://www.ftn-vakcine.rs/saglanost", "zanimanje_zaposlenog");
    private final static QName _Vakcinisanje_QNAME = new QName("http://www.ftn-vakcine.rs/saglanost", "vakcinisanje");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: saglasnost
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LicniPodaci }
     * 
     */
    public LicniPodaci createLicniPodaci() {
        return new LicniPodaci();
    }

    /**
     * Create an instance of {@link EvidencijaOVakcinaciji }
     * 
     */
    public EvidencijaOVakcinaciji createEvidencijaOVakcinaciji() {
        return new EvidencijaOVakcinaciji();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju }
     * 
     */
    public SaglasnostZaImunizaciju createSaglasnostZaImunizaciju() {
        return new SaglasnostZaImunizaciju();
    }

    /**
     * Create an instance of {@link TVakcinisanje }
     * 
     */
    public TVakcinisanje createTVakcinisanje() {
        return new TVakcinisanje();
    }

    /**
     * Create an instance of {@link Drzavljanstvo }
     * 
     */
    public Drzavljanstvo createDrzavljanstvo() {
        return new Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Srpsko }
     * 
     */
    public Srpsko createSrpsko() {
        return new Srpsko();
    }

    /**
     * Create an instance of {@link Strano }
     * 
     */
    public Strano createStrano() {
        return new Strano();
    }

    /**
     * Create an instance of {@link LicniPodaci.Adresa }
     * 
     */
    public LicniPodaci.Adresa createLicniPodaciAdresa() {
        return new LicniPodaci.Adresa();
    }

    /**
     * Create an instance of {@link LicniPodaci.KorisnikSocZastite }
     * 
     */
    public LicniPodaci.KorisnikSocZastite createLicniPodaciKorisnikSocZastite() {
        return new LicniPodaci.KorisnikSocZastite();
    }

    /**
     * Create an instance of {@link TLekar }
     * 
     */
    public TLekar createTLekar() {
        return new TLekar();
    }

    /**
     * Create an instance of {@link EvidencijaOVakcinaciji.TabelaVakcinisanja }
     * 
     */
    public EvidencijaOVakcinaciji.TabelaVakcinisanja createEvidencijaOVakcinacijiTabelaVakcinisanja() {
        return new EvidencijaOVakcinaciji.TabelaVakcinisanja();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Saglanost }
     * 
     */
    public SaglasnostZaImunizaciju.Saglanost createSaglasnostZaImunizacijuSaglanost() {
        return new SaglasnostZaImunizaciju.Saglanost();
    }

    /**
     * Create an instance of {@link ImePrezime }
     * 
     */
    public ImePrezime createImePrezime() {
        return new ImePrezime();
    }

    /**
     * Create an instance of {@link TVakcinisanje.PrivremeneKontraindikacije }
     * 
     */
    public TVakcinisanje.PrivremeneKontraindikacije createTVakcinisanjePrivremeneKontraindikacije() {
        return new TVakcinisanje.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/saglanost", name = "radni_status")
    public JAXBElement<String> createRadniStatus(String value) {
        return new JAXBElement<String>(_RadniStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLekar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/saglanost", name = "lekar")
    public JAXBElement<TLekar> createLekar(TLekar value) {
        return new JAXBElement<TLekar>(_Lekar_QNAME, TLekar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/saglanost", name = "zanimanje_zaposlenog")
    public JAXBElement<String> createZanimanjeZaposlenog(String value) {
        return new JAXBElement<String>(_ZanimanjeZaposlenog_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVakcinisanje }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn-vakcine.rs/saglanost", name = "vakcinisanje")
    public JAXBElement<TVakcinisanje> createVakcinisanje(TVakcinisanje value) {
        return new JAXBElement<TVakcinisanje>(_Vakcinisanje_QNAME, TVakcinisanje.class, null, value);
    }

}
