//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:58:55 PM CET 
//


package saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TVakcinisanje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TVakcinisanje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naziv_vakcine" type="{http://www.ftn-vakcine.rs/types}tip_vakcine"/>
 *         &lt;element name="datum_davanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ekstremitet">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="leva_ruka"/>
 *               &lt;enumeration value="desna_ruka"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="serija_vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proizvodjac" type="{http://www.ftn-vakcine.rs/types}tip_vakcine"/>
 *         &lt;element name="nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="potpis_lekara" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privremene_kontraindikacije">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVakcinisanje", propOrder = {
    "nazivVakcine",
    "datumDavanja",
    "nacinDavanja",
    "ekstremitet",
    "serijaVakcine",
    "proizvodjac",
    "nezeljenaReakcija",
    "potpisLekara",
    "privremeneKontraindikacije",
    "odlukaKomisije"
})
public class TVakcinisanje {

    @XmlElement(name = "naziv_vakcine", required = true)
    @XmlSchemaType(name = "string")
    protected TipVakcine nazivVakcine;
    @XmlElement(name = "datum_davanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDavanja;
    @XmlElement(name = "nacin_davanja", required = true)
    protected String nacinDavanja;
    @XmlElement(required = true)
    protected String ekstremitet;
    @XmlElement(name = "serija_vakcine", required = true)
    protected String serijaVakcine;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipVakcine proizvodjac;
    @XmlElement(name = "nezeljena_reakcija", required = true)
    protected String nezeljenaReakcija;
    @XmlElement(name = "potpis_lekara", required = true)
    protected String potpisLekara;
    @XmlElement(name = "privremene_kontraindikacije", required = true)
    protected TVakcinisanje.PrivremeneKontraindikacije privremeneKontraindikacije;
    @XmlElement(name = "odluka_komisije")
    protected String odlukaKomisije;

    /**
     * Gets the value of the nazivVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TipVakcine }
     *     
     */
    public TipVakcine getNazivVakcine() {
        return nazivVakcine;
    }

    /**
     * Sets the value of the nazivVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipVakcine }
     *     
     */
    public void setNazivVakcine(TipVakcine value) {
        this.nazivVakcine = value;
    }

    /**
     * Gets the value of the datumDavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDavanja() {
        return datumDavanja;
    }

    /**
     * Sets the value of the datumDavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDavanja(XMLGregorianCalendar value) {
        this.datumDavanja = value;
    }

    /**
     * Gets the value of the nacinDavanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinDavanja() {
        return nacinDavanja;
    }

    /**
     * Sets the value of the nacinDavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinDavanja(String value) {
        this.nacinDavanja = value;
    }

    /**
     * Gets the value of the ekstremitet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEkstremitet() {
        return ekstremitet;
    }

    /**
     * Sets the value of the ekstremitet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEkstremitet(String value) {
        this.ekstremitet = value;
    }

    /**
     * Gets the value of the serijaVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerijaVakcine() {
        return serijaVakcine;
    }

    /**
     * Sets the value of the serijaVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerijaVakcine(String value) {
        this.serijaVakcine = value;
    }

    /**
     * Gets the value of the proizvodjac property.
     * 
     * @return
     *     possible object is
     *     {@link TipVakcine }
     *     
     */
    public TipVakcine getProizvodjac() {
        return proizvodjac;
    }

    /**
     * Sets the value of the proizvodjac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipVakcine }
     *     
     */
    public void setProizvodjac(TipVakcine value) {
        this.proizvodjac = value;
    }

    /**
     * Gets the value of the nezeljenaReakcija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNezeljenaReakcija() {
        return nezeljenaReakcija;
    }

    /**
     * Sets the value of the nezeljenaReakcija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNezeljenaReakcija(String value) {
        this.nezeljenaReakcija = value;
    }

    /**
     * Gets the value of the potpisLekara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpisLekara() {
        return potpisLekara;
    }

    /**
     * Sets the value of the potpisLekara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpisLekara(String value) {
        this.potpisLekara = value;
    }

    /**
     * Gets the value of the privremeneKontraindikacije property.
     * 
     * @return
     *     possible object is
     *     {@link TVakcinisanje.PrivremeneKontraindikacije }
     *     
     */
    public TVakcinisanje.PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
        return privremeneKontraindikacije;
    }

    /**
     * Sets the value of the privremeneKontraindikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVakcinisanje.PrivremeneKontraindikacije }
     *     
     */
    public void setPrivremeneKontraindikacije(TVakcinisanje.PrivremeneKontraindikacije value) {
        this.privremeneKontraindikacije = value;
    }

    /**
     * Gets the value of the odlukaKomisije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdlukaKomisije() {
        return odlukaKomisije;
    }

    /**
     * Sets the value of the odlukaKomisije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdlukaKomisije(String value) {
        this.odlukaKomisije = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datum",
        "dijagnoza"
    })
    public static class PrivremeneKontraindikacije {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;
        @XmlElement(required = true)
        protected String dijagnoza;

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the dijagnoza property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDijagnoza() {
            return dijagnoza;
        }

        /**
         * Sets the value of the dijagnoza property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDijagnoza(String value) {
            this.dijagnoza = value;
        }

    }

}
