//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 09:58:14 PM CET 
//


package com.spring.rest.model.sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QR_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broj_sertifikata" type="{http://www.ftn-vakcine.rs/types}sifra"/>
 *         &lt;element name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/sertifikat}licni_podaci"/>
 *         &lt;element name="izdavac_sertifikata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/sertifikat}vakcinacije"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/sertifikat}testovi"/>
 *         &lt;element ref="{http://www.ftn-vakcine.rs/sertifikat}prelezana" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zahtev_za_sertifikat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="potvrda_o_vakcinisanju" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qrCode",
    "brojSertifikata",
    "datumIzdavanja",
    "licniPodaci",
    "izdavacSertifikata",
    "vakcinacije",
    "testovi",
    "prelezana"
})
@XmlRootElement(name = "zeleni_sertifikat")
public class ZeleniSertifikat {

    @XmlElement(name = "QR_code", required = true)
    protected String qrCode;
    @XmlElement(name = "broj_sertifikata", required = true)
    protected String brojSertifikata;
    @XmlElement(name = "datum_izdavanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;
    @XmlElement(name = "licni_podaci", required = true)
    protected TLicniPodaci licniPodaci;
    @XmlElement(name = "izdavac_sertifikata", required = true)
    protected String izdavacSertifikata;
    @XmlElement(required = true)
    protected Vakcinacije vakcinacije;
    @XmlElement(required = true)
    protected Testovi testovi;
    protected Prelezana prelezana;
    @XmlAttribute(name = "zahtev_za_sertifikat")
    protected String zahtevZaSertifikat;
    @XmlAttribute(name = "potvrda_o_vakcinisanju")
    @XmlSchemaType(name = "anySimpleType")
    protected String potvrdaOVakcinisanju;

    /**
     * Gets the value of the qrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRCode() {
        return qrCode;
    }

    /**
     * Sets the value of the qrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRCode(String value) {
        this.qrCode = value;
    }

    /**
     * Gets the value of the brojSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link TLicniPodaci }
     *     
     */
    public TLicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLicniPodaci }
     *     
     */
    public void setLicniPodaci(TLicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the izdavacSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIzdavacSertifikata() {
        return izdavacSertifikata;
    }

    /**
     * Sets the value of the izdavacSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIzdavacSertifikata(String value) {
        this.izdavacSertifikata = value;
    }

    /**
     * Gets the value of the vakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link Vakcinacije }
     *     
     */
    public Vakcinacije getVakcinacije() {
        return vakcinacije;
    }

    /**
     * Sets the value of the vakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vakcinacije }
     *     
     */
    public void setVakcinacije(Vakcinacije value) {
        this.vakcinacije = value;
    }

    /**
     * Gets the value of the testovi property.
     * 
     * @return
     *     possible object is
     *     {@link Testovi }
     *     
     */
    public Testovi getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testovi }
     *     
     */
    public void setTestovi(Testovi value) {
        this.testovi = value;
    }

    /**
     * Gets the value of the prelezana property.
     * 
     * @return
     *     possible object is
     *     {@link Prelezana }
     *     
     */
    public Prelezana getPrelezana() {
        return prelezana;
    }

    /**
     * Sets the value of the prelezana property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prelezana }
     *     
     */
    public void setPrelezana(Prelezana value) {
        this.prelezana = value;
    }

    /**
     * Gets the value of the zahtevZaSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevZaSertifikat() {
        return zahtevZaSertifikat;
    }

    /**
     * Sets the value of the zahtevZaSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevZaSertifikat(String value) {
        this.zahtevZaSertifikat = value;
    }

    /**
     * Gets the value of the potvrdaOVakcinisanju property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotvrdaOVakcinisanju() {
        return potvrdaOVakcinisanju;
    }

    /**
     * Sets the value of the potvrdaOVakcinisanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotvrdaOVakcinisanju(String value) {
        this.potvrdaOVakcinisanju = value;
    }

}
