//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:36:17 PM CET 
//


package com.spring.rest.model.sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QR_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broj_sertifikata" type="{http://ftn.uns.ac.rs/vakcina/tipovi}sifra"/>
 *         &lt;element name="datum_izdavanja">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/sertifikat}licni_podaci"/>
 *         &lt;element name="izdavac_sertifikata">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/sertifikat}vakcinacije"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/sertifikat}testovi"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/vakcina/sertifikat}prelezana" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zahtev_za_sertifikat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="potvrda_o_vakcinisanju" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qrCode",
    "brojSertifikata",
    "datumIzdavanja",
    "licniPodaci",
    "izdavacSertifikata",
    "vakcinacije",
    "testovi",
    "prelezana"
})
@XmlRootElement(name = "zeleni_sertifikat")
public class ZeleniSertifikat {

    @XmlElement(name = "QR_code", required = true)
    protected String qrCode;
    @XmlElement(name = "broj_sertifikata", required = true)
    protected String brojSertifikata;
    @XmlElement(name = "datum_izdavanja", required = true)
    protected DatumIzdavanja datumIzdavanja;
    @XmlElement(name = "licni_podaci", required = true)
    protected TLicniPodaci licniPodaci;
    @XmlElement(name = "izdavac_sertifikata", required = true)
    protected IzdavacSertifikata izdavacSertifikata;
    @XmlElement(required = true)
    protected Vakcinacije vakcinacije;
    @XmlElement(required = true)
    protected Testovi testovi;
    protected Prelezana prelezana;
    @XmlAttribute(name = "zahtev_za_sertifikat")
    protected String zahtevZaSertifikat;
    @XmlAttribute(name = "potvrda_o_vakcinisanju")
    @XmlSchemaType(name = "anySimpleType")
    protected String potvrdaOVakcinisanju;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anyURI")
    protected String about;
    @XmlAttribute(name = "rel")
    protected String rel;
    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anySimpleType")
    protected String href;

    /**
     * Gets the value of the qrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRCode() {
        return qrCode;
    }

    /**
     * Sets the value of the qrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRCode(String value) {
        this.qrCode = value;
    }

    /**
     * Gets the value of the brojSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link DatumIzdavanja }
     *     
     */
    public DatumIzdavanja getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumIzdavanja }
     *     
     */
    public void setDatumIzdavanja(DatumIzdavanja value) {
        this.datumIzdavanja = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link TLicniPodaci }
     *     
     */
    public TLicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLicniPodaci }
     *     
     */
    public void setLicniPodaci(TLicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the izdavacSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link IzdavacSertifikata }
     *     
     */
    public IzdavacSertifikata getIzdavacSertifikata() {
        return izdavacSertifikata;
    }

    /**
     * Sets the value of the izdavacSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzdavacSertifikata }
     *     
     */
    public void setIzdavacSertifikata(IzdavacSertifikata value) {
        this.izdavacSertifikata = value;
    }

    /**
     * Gets the value of the vakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link Vakcinacije }
     *     
     */
    public Vakcinacije getVakcinacije() {
        return vakcinacije;
    }

    /**
     * Sets the value of the vakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vakcinacije }
     *     
     */
    public void setVakcinacije(Vakcinacije value) {
        this.vakcinacije = value;
    }

    /**
     * Gets the value of the testovi property.
     * 
     * @return
     *     possible object is
     *     {@link Testovi }
     *     
     */
    public Testovi getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testovi }
     *     
     */
    public void setTestovi(Testovi value) {
        this.testovi = value;
    }

    /**
     * Gets the value of the prelezana property.
     * 
     * @return
     *     possible object is
     *     {@link Prelezana }
     *     
     */
    public Prelezana getPrelezana() {
        return prelezana;
    }

    /**
     * Sets the value of the prelezana property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prelezana }
     *     
     */
    public void setPrelezana(Prelezana value) {
        this.prelezana = value;
    }

    /**
     * Gets the value of the zahtevZaSertifikat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevZaSertifikat() {
        return zahtevZaSertifikat;
    }

    /**
     * Sets the value of the zahtevZaSertifikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevZaSertifikat(String value) {
        this.zahtevZaSertifikat = value;
    }

    /**
     * Gets the value of the potvrdaOVakcinisanju property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotvrdaOVakcinisanju() {
        return potvrdaOVakcinisanju;
    }

    /**
     * Sets the value of the potvrdaOVakcinisanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotvrdaOVakcinisanju(String value) {
        this.potvrdaOVakcinisanju = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    @Override
    public String toString() {
        return "ZeleniSertifikat{" +
                "qrCode='" + qrCode + '\'' +
                ", brojSertifikata='" + brojSertifikata + '\'' +
                ", datumIzdavanja=" + datumIzdavanja +
                ", licniPodaci=" + licniPodaci +
                ", izdavacSertifikata=" + izdavacSertifikata +
                ", vakcinacije=" + vakcinacije +
                ", testovi=" + testovi +
                ", prelezana=" + prelezana +
                ", zahtevZaSertifikat='" + zahtevZaSertifikat + '\'' +
                ", potvrdaOVakcinisanju='" + potvrdaOVakcinisanju + '\'' +
                ", id='" + id + '\'' +
                ", about='" + about + '\'' +
                ", rel='" + rel + '\'' +
                ", href='" + href + '\'' +
                '}';
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DatumIzdavanja {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class IzdavacSertifikata {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;
        @XmlAttribute(name = "datatype")
        @XmlSchemaType(name = "anySimpleType")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

}
