//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 07:36:09 PM CET 
//

<<<<<<< Updated upstream:Spring-JAX-RS/src/main/java/com/spring/rest/model/zahtev/package-info.java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/vakcina/zahtev", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
=======
<<<<<<< Updated upstream:Spring-JAX-RS/src/main/java/com/spring/rest/model/zahtev/package-info.java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn-vakcine.rs/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
>>>>>>> Stashed changes:Spring-JAX-RS/src/main/java/model/zahtev/package-info.java
package com.spring.rest.model.zahtev;
=======
@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/vakcina/zahtev", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.zahtev;
>>>>>>> Stashed changes:Spring-JAX-RS/src/main/java/model/zahtev/package-info.java
